### ISSUE TITLE
Simple use of MocketEntry broken

### ISSUE THREAD

**Issue by glandium** [mocketize/python-mocket#10]
Commit 37e1783a8cdad8b1eafbc31ff792ac0460393b10 changed MocketEntry.get_response to return response.data instead of str(response), and that doesn't work in the simple case where response_cls is str, like in the example from the presentation:

MocketEntry(('localhost', 8080), ['Show me.\r\n'])

**Comment by mindflayer** [comment]
I know it's really late. Solved in 1.2.4 version, btw.
