### ISSUE TITLE
mockhttp.Request doesn't like e.g. application/octet-stream contents

### ISSUE THREAD

**Issue by glandium** [mocketize/python-mocket#12]
When a received request is e.g. a PUT with application/octet-stream with raw non-ascii data, using mockhttp fails on this line:
_, self.body = decode_utf8(data).split('\r\n\r\n', 1)

**Comment by mindflayer** [comment]
I know it's been more than a year, but I'm back working on mocket.
I think I solved this issue when I added the support for file handlers. Have a look at this test:
https://github.com/mocketize/python-mocket/blob/master/tests/test_http.py#L143
