### ISSUE TITLE
Support for gevent sockets

### ISSUE THREAD

**Issue by thedrow** [mocketize/python-mocket#30]
I don't see any tests involving gevent.
Are gevent sockets supported?

**Comment by mindflayer** [comment]
Hi @thedrow, I've just run the tests adding
```
from gevent import monkey
monkey.patch_socket()
```
on top of _tests/test_http.py_ and they all succeeded.

**Comment by thedrow** [comment]
Yes it looks like it works. It might be worth adding to the test suite somehow though.

**Comment by mindflayer** [comment]
I had no doubts, by the way, since protocol does not change. :)

**Comment by mindflayer** [comment]
Adding `gevent` tests to `master` with #35 .
